q1 = input("Adjective")
q2 = input("Verb")
q3 = input("Noun")
q4 = input("Noun")
q5 = input("Adverb")
print(f"The {q1}astronaut decided")
print(f"to {q2} on Mars, Suddenly")
print(f"a {q3}stole all of")
print(f"their {q4} and ran away very {q5}")

