print("Welcome to the simple calculator!")
n1 = int(input("Enter the first number"))
n2 = int(input("Enter the second number"))
print(f"{n1} + {n2} = {n1 + n2}")
print(f"{n1} - {n2} = {n1 - n2}")
print(f"{n1} * {n2} = {n1 * n2}")
print(f"{n1} / {n2} = {n1 / n2}")